# Generated by Django 2.2.3 on 2019-08-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190809_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('NEW', 'primary'), ('SALE', 'secondary'), ('DISCOUNT', 'danger')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
