# Generated by Django 2.2.3 on 2019-07-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190727_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='slug-item', max_length=250, unique_for_date='added'),
            preserve_default=False,
        ),
    ]
