# Generated by Django 2.2.3 on 2019-07-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190728_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='added',
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
