# Generated by Django 2.2.3 on 2019-07-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_billing_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='countries',
            new_name='country',
        ),
    ]
